name: Security Audit

on:
  push:
    branches: ["main"]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  security_audit:
    name: Run cargo-deny check advisories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@cargo-deny

      - name: Run cargo-deny check advisories
        run: cargo deny check advisories
