name: Build

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
    secrets:
      GMAIL_CLIENT_ID:
        required: true
      GMAIL_CLIENT_SECRET:
        required: true
      OUTLOOK_CLIENT_ID:
        required: true

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          OUTLOOK_CLIENT_ID: ${{ secrets.OUTLOOK_CLIENT_ID }}
        with:
          command: build
          args: ${{ inputs.release && '--release' || '' }} --target ${{ matrix.target }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          OUTLOOK_CLIENT_ID: ${{ secrets.OUTLOOK_CLIENT_ID }}
        with:
          command: test
          args: --target ${{ matrix.target }}

      - name: Upload artifact
        if: inputs.release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/${{ inputs.release && 'release' || 'debug' }}/esim-mailer*
