name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release: true
    secrets: inherit

  release:
    needs: build
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: esim-mailer.exe
            asset_name: esim-mailer-windows-x64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: esim-mailer
            asset_name: esim-mailer-macos-x64.dmg
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: esim-mailer
            asset_name: esim-mailer-macos-arm64.dmg

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release

      - name: Install ImageMagick (macOS)
        if: runner.os == 'macOS'
        run: brew install imagemagick

      - name: Create .icns file (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir MyIcon.iconset
          for size in 16 32 64 128 256 512; do
            convert appIcon.png -resize ${size}x${size} MyIcon.iconset/icon_${size}x${size}.png
            convert appIcon.png -resize $((size*2))x$((size*2)) MyIcon.iconset/icon_${size}x${size}@2x.png
          done
          iconutil -c icns MyIcon.iconset
          mkdir -p ESim-Mailer.app/Contents/Resources
          mv MyIcon.icns ESim-Mailer.app/Contents/Resources/AppIcon.icns

      - name: Create .app bundle (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p ESim-Mailer.app/Contents/MacOS
          mkdir -p ESim-Mailer.app/Contents/Resources
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ESim-Mailer.app/Contents/MacOS/
          VERSION=${GITHUB_REF#refs/tags/v}
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleExecutable</key>
            <string>esim-mailer</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon</string>
            <key>CFBundleIdentifier</key>
            <string>com.petersonmichaelj.esim-mailer</string>
            <key>CFBundleName</key>
            <string>ESim Mailer</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>'$VERSION'</string>
            <key>CFBundleVersion</key>
            <string>'$VERSION'</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.11</string>
            <key>NSHighResolutionCapable</key>
            <true/>
          </dict>
          </plist>' > ESim-Mailer.app/Contents/Info.plist

      - name: Self-sign app (macOS)
        if: runner.os == 'macOS'
        run: |
          codesign --force --deep --sign - ESim-Mailer.app

      - name: Create DMG (macOS)
        if: runner.os == 'macOS'
        run: |
          hdiutil create -volname "ESim Mailer" -srcfolder ESim-Mailer.app -ov -format UDZO ${{ matrix.asset_name }}

      - name: Rename artifact (Windows)
        if: runner.os == 'Windows'
        run: move target\${{ matrix.target }}\release\${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}
