name: PR Checks

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      release: false
    secrets:
      GMAIL_CLIENT_ID: FakeSecret1
      GMAIL_CLIENT_SECRET: FakeSecret2
      OUTLOOK_CLIENT_ID: FakeSecret3
